// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        (unknown)
// source: wish/v1/wish.proto

package wish_v1

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Wish struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id      int64   `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	TgId    int64   `protobuf:"varint,2,opt,name=tg_id,json=tgId,proto3" json:"tg_id,omitempty"`
	Picture string  `protobuf:"bytes,3,opt,name=picture,proto3" json:"picture,omitempty"`
	Title   string  `protobuf:"bytes,4,opt,name=title,proto3" json:"title,omitempty"`
	Url     string  `protobuf:"bytes,5,opt,name=url,proto3" json:"url,omitempty"`
	Price   int64   `protobuf:"varint,6,opt,name=price,proto3" json:"price,omitempty"`
	Status  *Status `protobuf:"bytes,7,opt,name=status,proto3" json:"status,omitempty"`
}

func (x *Wish) Reset() {
	*x = Wish{}
	if protoimpl.UnsafeEnabled {
		mi := &file_wish_v1_wish_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Wish) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Wish) ProtoMessage() {}

func (x *Wish) ProtoReflect() protoreflect.Message {
	mi := &file_wish_v1_wish_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Wish.ProtoReflect.Descriptor instead.
func (*Wish) Descriptor() ([]byte, []int) {
	return file_wish_v1_wish_proto_rawDescGZIP(), []int{0}
}

func (x *Wish) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Wish) GetTgId() int64 {
	if x != nil {
		return x.TgId
	}
	return 0
}

func (x *Wish) GetPicture() string {
	if x != nil {
		return x.Picture
	}
	return ""
}

func (x *Wish) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *Wish) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

func (x *Wish) GetPrice() int64 {
	if x != nil {
		return x.Price
	}
	return 0
}

func (x *Wish) GetStatus() *Status {
	if x != nil {
		return x.Status
	}
	return nil
}

type Status struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id     int64  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	TgId   int64  `protobuf:"varint,2,opt,name=tg_id,json=tgId,proto3" json:"tg_id,omitempty"`
	Status string `protobuf:"bytes,3,opt,name=status,proto3" json:"status,omitempty"`
}

func (x *Status) Reset() {
	*x = Status{}
	if protoimpl.UnsafeEnabled {
		mi := &file_wish_v1_wish_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Status) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Status) ProtoMessage() {}

func (x *Status) ProtoReflect() protoreflect.Message {
	mi := &file_wish_v1_wish_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Status.ProtoReflect.Descriptor instead.
func (*Status) Descriptor() ([]byte, []int) {
	return file_wish_v1_wish_proto_rawDescGZIP(), []int{1}
}

func (x *Status) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Status) GetTgId() int64 {
	if x != nil {
		return x.TgId
	}
	return 0
}

func (x *Status) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

type GetWishByIdRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id int64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *GetWishByIdRequest) Reset() {
	*x = GetWishByIdRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_wish_v1_wish_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetWishByIdRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetWishByIdRequest) ProtoMessage() {}

func (x *GetWishByIdRequest) ProtoReflect() protoreflect.Message {
	mi := &file_wish_v1_wish_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetWishByIdRequest.ProtoReflect.Descriptor instead.
func (*GetWishByIdRequest) Descriptor() ([]byte, []int) {
	return file_wish_v1_wish_proto_rawDescGZIP(), []int{2}
}

func (x *GetWishByIdRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type GetWishByIdResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Wish *Wish `protobuf:"bytes,1,opt,name=wish,proto3" json:"wish,omitempty"`
}

func (x *GetWishByIdResponse) Reset() {
	*x = GetWishByIdResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_wish_v1_wish_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetWishByIdResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetWishByIdResponse) ProtoMessage() {}

func (x *GetWishByIdResponse) ProtoReflect() protoreflect.Message {
	mi := &file_wish_v1_wish_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetWishByIdResponse.ProtoReflect.Descriptor instead.
func (*GetWishByIdResponse) Descriptor() ([]byte, []int) {
	return file_wish_v1_wish_proto_rawDescGZIP(), []int{3}
}

func (x *GetWishByIdResponse) GetWish() *Wish {
	if x != nil {
		return x.Wish
	}
	return nil
}

type GetWishsRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	TgId int64 `protobuf:"varint,1,opt,name=tg_id,json=tgId,proto3" json:"tg_id,omitempty"`
}

func (x *GetWishsRequest) Reset() {
	*x = GetWishsRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_wish_v1_wish_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetWishsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetWishsRequest) ProtoMessage() {}

func (x *GetWishsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_wish_v1_wish_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetWishsRequest.ProtoReflect.Descriptor instead.
func (*GetWishsRequest) Descriptor() ([]byte, []int) {
	return file_wish_v1_wish_proto_rawDescGZIP(), []int{4}
}

func (x *GetWishsRequest) GetTgId() int64 {
	if x != nil {
		return x.TgId
	}
	return 0
}

type GetWishsResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Wishs []*Wish `protobuf:"bytes,1,rep,name=wishs,proto3" json:"wishs,omitempty"`
}

func (x *GetWishsResponse) Reset() {
	*x = GetWishsResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_wish_v1_wish_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetWishsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetWishsResponse) ProtoMessage() {}

func (x *GetWishsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_wish_v1_wish_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetWishsResponse.ProtoReflect.Descriptor instead.
func (*GetWishsResponse) Descriptor() ([]byte, []int) {
	return file_wish_v1_wish_proto_rawDescGZIP(), []int{5}
}

func (x *GetWishsResponse) GetWishs() []*Wish {
	if x != nil {
		return x.Wishs
	}
	return nil
}

type CreateWishRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	TgId    int64  `protobuf:"varint,1,opt,name=tg_id,json=tgId,proto3" json:"tg_id,omitempty"`
	Picture string `protobuf:"bytes,2,opt,name=picture,proto3" json:"picture,omitempty"`
	Price   int64  `protobuf:"varint,3,opt,name=price,proto3" json:"price,omitempty"`
	Title   string `protobuf:"bytes,4,opt,name=title,proto3" json:"title,omitempty"`
	Url     string `protobuf:"bytes,5,opt,name=url,proto3" json:"url,omitempty"`
}

func (x *CreateWishRequest) Reset() {
	*x = CreateWishRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_wish_v1_wish_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateWishRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateWishRequest) ProtoMessage() {}

func (x *CreateWishRequest) ProtoReflect() protoreflect.Message {
	mi := &file_wish_v1_wish_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateWishRequest.ProtoReflect.Descriptor instead.
func (*CreateWishRequest) Descriptor() ([]byte, []int) {
	return file_wish_v1_wish_proto_rawDescGZIP(), []int{6}
}

func (x *CreateWishRequest) GetTgId() int64 {
	if x != nil {
		return x.TgId
	}
	return 0
}

func (x *CreateWishRequest) GetPicture() string {
	if x != nil {
		return x.Picture
	}
	return ""
}

func (x *CreateWishRequest) GetPrice() int64 {
	if x != nil {
		return x.Price
	}
	return 0
}

func (x *CreateWishRequest) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *CreateWishRequest) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

type CreateWishResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id int64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *CreateWishResponse) Reset() {
	*x = CreateWishResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_wish_v1_wish_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateWishResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateWishResponse) ProtoMessage() {}

func (x *CreateWishResponse) ProtoReflect() protoreflect.Message {
	mi := &file_wish_v1_wish_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateWishResponse.ProtoReflect.Descriptor instead.
func (*CreateWishResponse) Descriptor() ([]byte, []int) {
	return file_wish_v1_wish_proto_rawDescGZIP(), []int{7}
}

func (x *CreateWishResponse) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type DeleteWishRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	TgId   int64 `protobuf:"varint,1,opt,name=tg_id,json=tgId,proto3" json:"tg_id,omitempty"`
	WishId int64 `protobuf:"varint,2,opt,name=wish_id,json=wishId,proto3" json:"wish_id,omitempty"`
}

func (x *DeleteWishRequest) Reset() {
	*x = DeleteWishRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_wish_v1_wish_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeleteWishRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteWishRequest) ProtoMessage() {}

func (x *DeleteWishRequest) ProtoReflect() protoreflect.Message {
	mi := &file_wish_v1_wish_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteWishRequest.ProtoReflect.Descriptor instead.
func (*DeleteWishRequest) Descriptor() ([]byte, []int) {
	return file_wish_v1_wish_proto_rawDescGZIP(), []int{8}
}

func (x *DeleteWishRequest) GetTgId() int64 {
	if x != nil {
		return x.TgId
	}
	return 0
}

func (x *DeleteWishRequest) GetWishId() int64 {
	if x != nil {
		return x.WishId
	}
	return 0
}

type DeleteWishResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *DeleteWishResponse) Reset() {
	*x = DeleteWishResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_wish_v1_wish_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeleteWishResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteWishResponse) ProtoMessage() {}

func (x *DeleteWishResponse) ProtoReflect() protoreflect.Message {
	mi := &file_wish_v1_wish_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteWishResponse.ProtoReflect.Descriptor instead.
func (*DeleteWishResponse) Descriptor() ([]byte, []int) {
	return file_wish_v1_wish_proto_rawDescGZIP(), []int{9}
}

type UpdateStatusWishRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	TgId   int64  `protobuf:"varint,1,opt,name=tg_id,json=tgId,proto3" json:"tg_id,omitempty"`
	WishId int64  `protobuf:"varint,2,opt,name=wish_id,json=wishId,proto3" json:"wish_id,omitempty"`
	Status string `protobuf:"bytes,3,opt,name=status,proto3" json:"status,omitempty"`
}

func (x *UpdateStatusWishRequest) Reset() {
	*x = UpdateStatusWishRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_wish_v1_wish_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdateStatusWishRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateStatusWishRequest) ProtoMessage() {}

func (x *UpdateStatusWishRequest) ProtoReflect() protoreflect.Message {
	mi := &file_wish_v1_wish_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateStatusWishRequest.ProtoReflect.Descriptor instead.
func (*UpdateStatusWishRequest) Descriptor() ([]byte, []int) {
	return file_wish_v1_wish_proto_rawDescGZIP(), []int{10}
}

func (x *UpdateStatusWishRequest) GetTgId() int64 {
	if x != nil {
		return x.TgId
	}
	return 0
}

func (x *UpdateStatusWishRequest) GetWishId() int64 {
	if x != nil {
		return x.WishId
	}
	return 0
}

func (x *UpdateStatusWishRequest) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

type UpdateStatusWishResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *UpdateStatusWishResponse) Reset() {
	*x = UpdateStatusWishResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_wish_v1_wish_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdateStatusWishResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateStatusWishResponse) ProtoMessage() {}

func (x *UpdateStatusWishResponse) ProtoReflect() protoreflect.Message {
	mi := &file_wish_v1_wish_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateStatusWishResponse.ProtoReflect.Descriptor instead.
func (*UpdateStatusWishResponse) Descriptor() ([]byte, []int) {
	return file_wish_v1_wish_proto_rawDescGZIP(), []int{11}
}

var File_wish_v1_wish_proto protoreflect.FileDescriptor

var file_wish_v1_wish_proto_rawDesc = []byte{
	0x0a, 0x12, 0x77, 0x69, 0x73, 0x68, 0x2f, 0x76, 0x31, 0x2f, 0x77, 0x69, 0x73, 0x68, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x12, 0x07, 0x75, 0x73, 0x65, 0x72, 0x2e, 0x76, 0x31, 0x1a, 0x1c, 0x67,
	0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x61, 0x6e, 0x6e, 0x6f, 0x74, 0x61,
	0x74, 0x69, 0x6f, 0x6e, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0xac, 0x01, 0x0a, 0x04,
	0x57, 0x69, 0x73, 0x68, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03,
	0x52, 0x02, 0x69, 0x64, 0x12, 0x13, 0x0a, 0x05, 0x74, 0x67, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x03, 0x52, 0x04, 0x74, 0x67, 0x49, 0x64, 0x12, 0x18, 0x0a, 0x07, 0x70, 0x69, 0x63,
	0x74, 0x75, 0x72, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x70, 0x69, 0x63, 0x74,
	0x75, 0x72, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x74, 0x69, 0x74, 0x6c, 0x65, 0x18, 0x04, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x05, 0x74, 0x69, 0x74, 0x6c, 0x65, 0x12, 0x10, 0x0a, 0x03, 0x75, 0x72, 0x6c,
	0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x75, 0x72, 0x6c, 0x12, 0x14, 0x0a, 0x05, 0x70,
	0x72, 0x69, 0x63, 0x65, 0x18, 0x06, 0x20, 0x01, 0x28, 0x03, 0x52, 0x05, 0x70, 0x72, 0x69, 0x63,
	0x65, 0x12, 0x27, 0x0a, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x07, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x0f, 0x2e, 0x75, 0x73, 0x65, 0x72, 0x2e, 0x76, 0x31, 0x2e, 0x53, 0x74, 0x61, 0x74,
	0x75, 0x73, 0x52, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x22, 0x45, 0x0a, 0x06, 0x53, 0x74,
	0x61, 0x74, 0x75, 0x73, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03,
	0x52, 0x02, 0x69, 0x64, 0x12, 0x13, 0x0a, 0x05, 0x74, 0x67, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x03, 0x52, 0x04, 0x74, 0x67, 0x49, 0x64, 0x12, 0x16, 0x0a, 0x06, 0x73, 0x74, 0x61,
	0x74, 0x75, 0x73, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75,
	0x73, 0x22, 0x24, 0x0a, 0x12, 0x47, 0x65, 0x74, 0x57, 0x69, 0x73, 0x68, 0x42, 0x79, 0x49, 0x64,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x03, 0x52, 0x02, 0x69, 0x64, 0x22, 0x38, 0x0a, 0x13, 0x47, 0x65, 0x74, 0x57, 0x69,
	0x73, 0x68, 0x42, 0x79, 0x49, 0x64, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x21,
	0x0a, 0x04, 0x77, 0x69, 0x73, 0x68, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0d, 0x2e, 0x75,
	0x73, 0x65, 0x72, 0x2e, 0x76, 0x31, 0x2e, 0x57, 0x69, 0x73, 0x68, 0x52, 0x04, 0x77, 0x69, 0x73,
	0x68, 0x22, 0x26, 0x0a, 0x0f, 0x47, 0x65, 0x74, 0x57, 0x69, 0x73, 0x68, 0x73, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x12, 0x13, 0x0a, 0x05, 0x74, 0x67, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x03, 0x52, 0x04, 0x74, 0x67, 0x49, 0x64, 0x22, 0x37, 0x0a, 0x10, 0x47, 0x65, 0x74,
	0x57, 0x69, 0x73, 0x68, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x23, 0x0a,
	0x05, 0x77, 0x69, 0x73, 0x68, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0d, 0x2e, 0x75,
	0x73, 0x65, 0x72, 0x2e, 0x76, 0x31, 0x2e, 0x57, 0x69, 0x73, 0x68, 0x52, 0x05, 0x77, 0x69, 0x73,
	0x68, 0x73, 0x22, 0x80, 0x01, 0x0a, 0x11, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x57, 0x69, 0x73,
	0x68, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x13, 0x0a, 0x05, 0x74, 0x67, 0x5f, 0x69,
	0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x04, 0x74, 0x67, 0x49, 0x64, 0x12, 0x18, 0x0a,
	0x07, 0x70, 0x69, 0x63, 0x74, 0x75, 0x72, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07,
	0x70, 0x69, 0x63, 0x74, 0x75, 0x72, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x70, 0x72, 0x69, 0x63, 0x65,
	0x18, 0x03, 0x20, 0x01, 0x28, 0x03, 0x52, 0x05, 0x70, 0x72, 0x69, 0x63, 0x65, 0x12, 0x14, 0x0a,
	0x05, 0x74, 0x69, 0x74, 0x6c, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x74, 0x69,
	0x74, 0x6c, 0x65, 0x12, 0x10, 0x0a, 0x03, 0x75, 0x72, 0x6c, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x03, 0x75, 0x72, 0x6c, 0x22, 0x24, 0x0a, 0x12, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x57,
	0x69, 0x73, 0x68, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x0e, 0x0a, 0x02, 0x69,
	0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x02, 0x69, 0x64, 0x22, 0x41, 0x0a, 0x11, 0x44,
	0x65, 0x6c, 0x65, 0x74, 0x65, 0x57, 0x69, 0x73, 0x68, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x12, 0x13, 0x0a, 0x05, 0x74, 0x67, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52,
	0x04, 0x74, 0x67, 0x49, 0x64, 0x12, 0x17, 0x0a, 0x07, 0x77, 0x69, 0x73, 0x68, 0x5f, 0x69, 0x64,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x06, 0x77, 0x69, 0x73, 0x68, 0x49, 0x64, 0x22, 0x14,
	0x0a, 0x12, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x57, 0x69, 0x73, 0x68, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x22, 0x5f, 0x0a, 0x17, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x53, 0x74,
	0x61, 0x74, 0x75, 0x73, 0x57, 0x69, 0x73, 0x68, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12,
	0x13, 0x0a, 0x05, 0x74, 0x67, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x04,
	0x74, 0x67, 0x49, 0x64, 0x12, 0x17, 0x0a, 0x07, 0x77, 0x69, 0x73, 0x68, 0x5f, 0x69, 0x64, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x06, 0x77, 0x69, 0x73, 0x68, 0x49, 0x64, 0x12, 0x16, 0x0a,
	0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x73,
	0x74, 0x61, 0x74, 0x75, 0x73, 0x22, 0x1a, 0x0a, 0x18, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x53,
	0x74, 0x61, 0x74, 0x75, 0x73, 0x57, 0x69, 0x73, 0x68, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x32, 0xb0, 0x04, 0x0a, 0x06, 0x57, 0x69, 0x73, 0x68, 0x56, 0x31, 0x12, 0x48, 0x0a, 0x0b,
	0x47, 0x65, 0x74, 0x57, 0x69, 0x73, 0x68, 0x42, 0x79, 0x49, 0x64, 0x12, 0x1b, 0x2e, 0x75, 0x73,
	0x65, 0x72, 0x2e, 0x76, 0x31, 0x2e, 0x47, 0x65, 0x74, 0x57, 0x69, 0x73, 0x68, 0x42, 0x79, 0x49,
	0x64, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1c, 0x2e, 0x75, 0x73, 0x65, 0x72, 0x2e,
	0x76, 0x31, 0x2e, 0x47, 0x65, 0x74, 0x57, 0x69, 0x73, 0x68, 0x42, 0x79, 0x49, 0x64, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x65, 0x0a, 0x08, 0x47, 0x65, 0x74, 0x57, 0x69, 0x73,
	0x68, 0x73, 0x12, 0x18, 0x2e, 0x75, 0x73, 0x65, 0x72, 0x2e, 0x76, 0x31, 0x2e, 0x47, 0x65, 0x74,
	0x57, 0x69, 0x73, 0x68, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x19, 0x2e, 0x75,
	0x73, 0x65, 0x72, 0x2e, 0x76, 0x31, 0x2e, 0x47, 0x65, 0x74, 0x57, 0x69, 0x73, 0x68, 0x73, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x24, 0x82, 0xd3, 0xe4, 0x93, 0x02, 0x1e, 0x12,
	0x1c, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x76, 0x31, 0x2f, 0x75, 0x73, 0x65, 0x72, 0x73, 0x2f, 0x7b,
	0x74, 0x67, 0x5f, 0x69, 0x64, 0x7d, 0x2f, 0x77, 0x69, 0x73, 0x68, 0x65, 0x73, 0x12, 0x6e, 0x0a,
	0x0a, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x57, 0x69, 0x73, 0x68, 0x12, 0x1a, 0x2e, 0x75, 0x73,
	0x65, 0x72, 0x2e, 0x76, 0x31, 0x2e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x57, 0x69, 0x73, 0x68,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1b, 0x2e, 0x75, 0x73, 0x65, 0x72, 0x2e, 0x76,
	0x31, 0x2e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x57, 0x69, 0x73, 0x68, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x22, 0x27, 0x82, 0xd3, 0xe4, 0x93, 0x02, 0x21, 0x3a, 0x01, 0x2a, 0x22,
	0x1c, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x76, 0x31, 0x2f, 0x75, 0x73, 0x65, 0x72, 0x73, 0x2f, 0x7b,
	0x74, 0x67, 0x5f, 0x69, 0x64, 0x7d, 0x2f, 0x77, 0x69, 0x73, 0x68, 0x65, 0x73, 0x12, 0x75, 0x0a,
	0x0a, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x57, 0x69, 0x73, 0x68, 0x12, 0x1a, 0x2e, 0x75, 0x73,
	0x65, 0x72, 0x2e, 0x76, 0x31, 0x2e, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x57, 0x69, 0x73, 0x68,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1b, 0x2e, 0x75, 0x73, 0x65, 0x72, 0x2e, 0x76,
	0x31, 0x2e, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x57, 0x69, 0x73, 0x68, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x22, 0x2e, 0x82, 0xd3, 0xe4, 0x93, 0x02, 0x28, 0x2a, 0x26, 0x2f, 0x61,
	0x70, 0x69, 0x2f, 0x76, 0x31, 0x2f, 0x75, 0x73, 0x65, 0x72, 0x73, 0x2f, 0x7b, 0x74, 0x67, 0x5f,
	0x69, 0x64, 0x7d, 0x2f, 0x77, 0x69, 0x73, 0x68, 0x65, 0x73, 0x2f, 0x7b, 0x77, 0x69, 0x73, 0x68,
	0x5f, 0x69, 0x64, 0x7d, 0x12, 0x8d, 0x01, 0x0a, 0x0c, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x53,
	0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x20, 0x2e, 0x75, 0x73, 0x65, 0x72, 0x2e, 0x76, 0x31, 0x2e,
	0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x57, 0x69, 0x73, 0x68,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x21, 0x2e, 0x75, 0x73, 0x65, 0x72, 0x2e, 0x76,
	0x31, 0x2e, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x57, 0x69,
	0x73, 0x68, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x38, 0x82, 0xd3, 0xe4, 0x93,
	0x02, 0x32, 0x3a, 0x01, 0x2a, 0x32, 0x2d, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x76, 0x31, 0x2f, 0x75,
	0x73, 0x65, 0x72, 0x73, 0x2f, 0x7b, 0x74, 0x67, 0x5f, 0x69, 0x64, 0x7d, 0x2f, 0x77, 0x69, 0x73,
	0x68, 0x65, 0x73, 0x2f, 0x7b, 0x77, 0x69, 0x73, 0x68, 0x5f, 0x69, 0x64, 0x7d, 0x2f, 0x73, 0x74,
	0x61, 0x74, 0x75, 0x73, 0x42, 0x54, 0x5a, 0x52, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63,
	0x6f, 0x6d, 0x2f, 0x52, 0x53, 0x4f, 0x44, 0x41, 0x2f, 0x77, 0x69, 0x73, 0x68, 0x6c, 0x69, 0x73,
	0x74, 0x2f, 0x6d, 0x69, 0x63, 0x72, 0x6f, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x73, 0x2f,
	0x77, 0x69, 0x73, 0x68, 0x6c, 0x69, 0x73, 0x74, 0x5f, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65,
	0x2f, 0x70, 0x6b, 0x67, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x77, 0x69, 0x73, 0x68, 0x2f,
	0x76, 0x31, 0x3b, 0x77, 0x69, 0x73, 0x68, 0x5f, 0x76, 0x31, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x33,
}

var (
	file_wish_v1_wish_proto_rawDescOnce sync.Once
	file_wish_v1_wish_proto_rawDescData = file_wish_v1_wish_proto_rawDesc
)

func file_wish_v1_wish_proto_rawDescGZIP() []byte {
	file_wish_v1_wish_proto_rawDescOnce.Do(func() {
		file_wish_v1_wish_proto_rawDescData = protoimpl.X.CompressGZIP(file_wish_v1_wish_proto_rawDescData)
	})
	return file_wish_v1_wish_proto_rawDescData
}

var file_wish_v1_wish_proto_msgTypes = make([]protoimpl.MessageInfo, 12)
var file_wish_v1_wish_proto_goTypes = []interface{}{
	(*Wish)(nil),                     // 0: user.v1.Wish
	(*Status)(nil),                   // 1: user.v1.Status
	(*GetWishByIdRequest)(nil),       // 2: user.v1.GetWishByIdRequest
	(*GetWishByIdResponse)(nil),      // 3: user.v1.GetWishByIdResponse
	(*GetWishsRequest)(nil),          // 4: user.v1.GetWishsRequest
	(*GetWishsResponse)(nil),         // 5: user.v1.GetWishsResponse
	(*CreateWishRequest)(nil),        // 6: user.v1.CreateWishRequest
	(*CreateWishResponse)(nil),       // 7: user.v1.CreateWishResponse
	(*DeleteWishRequest)(nil),        // 8: user.v1.DeleteWishRequest
	(*DeleteWishResponse)(nil),       // 9: user.v1.DeleteWishResponse
	(*UpdateStatusWishRequest)(nil),  // 10: user.v1.UpdateStatusWishRequest
	(*UpdateStatusWishResponse)(nil), // 11: user.v1.UpdateStatusWishResponse
}
var file_wish_v1_wish_proto_depIdxs = []int32{
	1,  // 0: user.v1.Wish.status:type_name -> user.v1.Status
	0,  // 1: user.v1.GetWishByIdResponse.wish:type_name -> user.v1.Wish
	0,  // 2: user.v1.GetWishsResponse.wishs:type_name -> user.v1.Wish
	2,  // 3: user.v1.WishV1.GetWishById:input_type -> user.v1.GetWishByIdRequest
	4,  // 4: user.v1.WishV1.GetWishs:input_type -> user.v1.GetWishsRequest
	6,  // 5: user.v1.WishV1.CreateWish:input_type -> user.v1.CreateWishRequest
	8,  // 6: user.v1.WishV1.DeleteWish:input_type -> user.v1.DeleteWishRequest
	10, // 7: user.v1.WishV1.UpdateStatus:input_type -> user.v1.UpdateStatusWishRequest
	3,  // 8: user.v1.WishV1.GetWishById:output_type -> user.v1.GetWishByIdResponse
	5,  // 9: user.v1.WishV1.GetWishs:output_type -> user.v1.GetWishsResponse
	7,  // 10: user.v1.WishV1.CreateWish:output_type -> user.v1.CreateWishResponse
	9,  // 11: user.v1.WishV1.DeleteWish:output_type -> user.v1.DeleteWishResponse
	11, // 12: user.v1.WishV1.UpdateStatus:output_type -> user.v1.UpdateStatusWishResponse
	8,  // [8:13] is the sub-list for method output_type
	3,  // [3:8] is the sub-list for method input_type
	3,  // [3:3] is the sub-list for extension type_name
	3,  // [3:3] is the sub-list for extension extendee
	0,  // [0:3] is the sub-list for field type_name
}

func init() { file_wish_v1_wish_proto_init() }
func file_wish_v1_wish_proto_init() {
	if File_wish_v1_wish_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_wish_v1_wish_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Wish); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_wish_v1_wish_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Status); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_wish_v1_wish_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetWishByIdRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_wish_v1_wish_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetWishByIdResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_wish_v1_wish_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetWishsRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_wish_v1_wish_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetWishsResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_wish_v1_wish_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateWishRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_wish_v1_wish_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateWishResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_wish_v1_wish_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeleteWishRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_wish_v1_wish_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeleteWishResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_wish_v1_wish_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UpdateStatusWishRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_wish_v1_wish_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UpdateStatusWishResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_wish_v1_wish_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   12,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_wish_v1_wish_proto_goTypes,
		DependencyIndexes: file_wish_v1_wish_proto_depIdxs,
		MessageInfos:      file_wish_v1_wish_proto_msgTypes,
	}.Build()
	File_wish_v1_wish_proto = out.File
	file_wish_v1_wish_proto_rawDesc = nil
	file_wish_v1_wish_proto_goTypes = nil
	file_wish_v1_wish_proto_depIdxs = nil
}
