// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             (unknown)
// source: wish/v1/wish.proto

package wish_v1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// WishV1Client is the client API for WishV1 service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type WishV1Client interface {
	GetWishById(ctx context.Context, in *GetWishByIdRequest, opts ...grpc.CallOption) (*GetWishByIdResponse, error)
	GetWishs(ctx context.Context, in *GetWishsRequest, opts ...grpc.CallOption) (*GetWishsResponse, error)
	CreateWish(ctx context.Context, in *CreateWishRequest, opts ...grpc.CallOption) (*CreateWishResponse, error)
	DeleteWish(ctx context.Context, in *DeleteWishRequest, opts ...grpc.CallOption) (*DeleteWishResponse, error)
	UpdateStatus(ctx context.Context, in *UpdateStatusWishRequest, opts ...grpc.CallOption) (*UpdateStatusWishResponse, error)
}

type wishV1Client struct {
	cc grpc.ClientConnInterface
}

func NewWishV1Client(cc grpc.ClientConnInterface) WishV1Client {
	return &wishV1Client{cc}
}

func (c *wishV1Client) GetWishById(ctx context.Context, in *GetWishByIdRequest, opts ...grpc.CallOption) (*GetWishByIdResponse, error) {
	out := new(GetWishByIdResponse)
	err := c.cc.Invoke(ctx, "/user.v1.WishV1/GetWishById", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *wishV1Client) GetWishs(ctx context.Context, in *GetWishsRequest, opts ...grpc.CallOption) (*GetWishsResponse, error) {
	out := new(GetWishsResponse)
	err := c.cc.Invoke(ctx, "/user.v1.WishV1/GetWishs", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *wishV1Client) CreateWish(ctx context.Context, in *CreateWishRequest, opts ...grpc.CallOption) (*CreateWishResponse, error) {
	out := new(CreateWishResponse)
	err := c.cc.Invoke(ctx, "/user.v1.WishV1/CreateWish", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *wishV1Client) DeleteWish(ctx context.Context, in *DeleteWishRequest, opts ...grpc.CallOption) (*DeleteWishResponse, error) {
	out := new(DeleteWishResponse)
	err := c.cc.Invoke(ctx, "/user.v1.WishV1/DeleteWish", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *wishV1Client) UpdateStatus(ctx context.Context, in *UpdateStatusWishRequest, opts ...grpc.CallOption) (*UpdateStatusWishResponse, error) {
	out := new(UpdateStatusWishResponse)
	err := c.cc.Invoke(ctx, "/user.v1.WishV1/UpdateStatus", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// WishV1Server is the server API for WishV1 service.
// All implementations must embed UnimplementedWishV1Server
// for forward compatibility
type WishV1Server interface {
	GetWishById(context.Context, *GetWishByIdRequest) (*GetWishByIdResponse, error)
	GetWishs(context.Context, *GetWishsRequest) (*GetWishsResponse, error)
	CreateWish(context.Context, *CreateWishRequest) (*CreateWishResponse, error)
	DeleteWish(context.Context, *DeleteWishRequest) (*DeleteWishResponse, error)
	UpdateStatus(context.Context, *UpdateStatusWishRequest) (*UpdateStatusWishResponse, error)
	mustEmbedUnimplementedWishV1Server()
}

// UnimplementedWishV1Server must be embedded to have forward compatible implementations.
type UnimplementedWishV1Server struct {
}

func (UnimplementedWishV1Server) GetWishById(context.Context, *GetWishByIdRequest) (*GetWishByIdResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetWishById not implemented")
}
func (UnimplementedWishV1Server) GetWishs(context.Context, *GetWishsRequest) (*GetWishsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetWishs not implemented")
}
func (UnimplementedWishV1Server) CreateWish(context.Context, *CreateWishRequest) (*CreateWishResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateWish not implemented")
}
func (UnimplementedWishV1Server) DeleteWish(context.Context, *DeleteWishRequest) (*DeleteWishResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteWish not implemented")
}
func (UnimplementedWishV1Server) UpdateStatus(context.Context, *UpdateStatusWishRequest) (*UpdateStatusWishResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateStatus not implemented")
}
func (UnimplementedWishV1Server) mustEmbedUnimplementedWishV1Server() {}

// UnsafeWishV1Server may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to WishV1Server will
// result in compilation errors.
type UnsafeWishV1Server interface {
	mustEmbedUnimplementedWishV1Server()
}

func RegisterWishV1Server(s grpc.ServiceRegistrar, srv WishV1Server) {
	s.RegisterService(&WishV1_ServiceDesc, srv)
}

func _WishV1_GetWishById_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetWishByIdRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WishV1Server).GetWishById(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/user.v1.WishV1/GetWishById",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WishV1Server).GetWishById(ctx, req.(*GetWishByIdRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WishV1_GetWishs_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetWishsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WishV1Server).GetWishs(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/user.v1.WishV1/GetWishs",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WishV1Server).GetWishs(ctx, req.(*GetWishsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WishV1_CreateWish_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateWishRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WishV1Server).CreateWish(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/user.v1.WishV1/CreateWish",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WishV1Server).CreateWish(ctx, req.(*CreateWishRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WishV1_DeleteWish_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteWishRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WishV1Server).DeleteWish(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/user.v1.WishV1/DeleteWish",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WishV1Server).DeleteWish(ctx, req.(*DeleteWishRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WishV1_UpdateStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateStatusWishRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WishV1Server).UpdateStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/user.v1.WishV1/UpdateStatus",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WishV1Server).UpdateStatus(ctx, req.(*UpdateStatusWishRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// WishV1_ServiceDesc is the grpc.ServiceDesc for WishV1 service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var WishV1_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "user.v1.WishV1",
	HandlerType: (*WishV1Server)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetWishById",
			Handler:    _WishV1_GetWishById_Handler,
		},
		{
			MethodName: "GetWishs",
			Handler:    _WishV1_GetWishs_Handler,
		},
		{
			MethodName: "CreateWish",
			Handler:    _WishV1_CreateWish_Handler,
		},
		{
			MethodName: "DeleteWish",
			Handler:    _WishV1_DeleteWish_Handler,
		},
		{
			MethodName: "UpdateStatus",
			Handler:    _WishV1_UpdateStatus_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "wish/v1/wish.proto",
}
