syntax = "proto3";

package user.v1;

option go_package = "github.com/RSODA/wishlist/pkg/proto/user/v1;user_v1";

import "google/api/annotations.proto";

service UserV1 {
  rpc GetSub(GetSubRequest) returns (GetSubResponse) {
    option (google.api.http) = {
      get: "/api/v1/user/{tg_id}"
    };
  };
  rpc Subscribe(SubscribeRequest) returns (SubscribeResponse) {
    option (google.api.http) = {
      post: "/api/v1/user/subscribe"
      body: "*"
    };
  };
  rpc CreateUser(CreateUserRequest) returns (CreateUserResponse) {
    option (google.api.http) = {
      post: "/api/v1/user"
      body: "*"
    };
  };
  rpc AcceptedSub(AcceptedSubRequest) returns (AcceptedSubResponse) {
    option (google.api.http) = {
      put: "/api/v1/user/accepted-sub"
      body: "*"
    };
  };
  rpc CheckSubIsAccepted(CheckSubIsAcceptedRequest) returns (CheckSubIsAcceptedResponse);
}

message User {
  int64 id = 1;
  string name = 2;
  int64 tg_id = 3;
  repeated Subscribe subscribe = 4;
}

message Subscribe {
  int64 tg_id = 1;
  string username = 2;
  bool is_accepted = 3;
}

message GetUserRequest {
  int64 tg_id = 1;
}

message GetUserResponse {
    User user = 1;
}

message GetSubRequest {
  int64 tg_id = 1;
}

message GetSubResponse {
  string username = 1;
  repeated Subscribe follower_to = 2;
  repeated Subscribe follower_from = 3;
}

message SubscribeRequest {
  string to_username = 2;
}

message SubscribeResponse {}

message CreateUserRequest {
  int64 tg_id = 1;
  string username = 2;
}

message CreateUserResponse {
  User user = 1;
}

message AcceptedSubRequest {
  int64 accepted_tg_id = 1;
}

message AcceptedSubResponse {}

message CheckSubIsAcceptedRequest {
  int64 from_tg_id = 1;
  int64 to_tg_id = 2;
}

message CheckSubIsAcceptedResponse {
  bool is_accepted = 1;
}
